# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MWVmZDA5ODI1NDY3MzlkYzk4MjY4ODliOWMwYTU1MGI3ZGFmN2E0NTk0NjJjZWZhZWQ4YWRlZWM4ZjRjNzhmY2RmODYxZjJmNzljY2ZjOWY0ODIwOTYxNjZjMTY4MmM3NTQwYmEyODBhMzg3MmY0Njc5MWViOWY2OTYyZGRhYWY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
