#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZGZjNGQzZTkyMjNkZDU3NTE4OTM1YmI2OWU3ZWZlYTEwZThkOGY0ODc1MWQwYWRlNTQzYjRhOGUxNzVhNDhjYTYwMzk5YWY3YWJiNGYyNDc1MTJlOTY0N2RjZjdlOTVlYWEzNA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
